### ISSUE TITLE
Include rangefinder in the estimation

### ISSUE THREAD

**Issue by juangallostra** [juangallostra/AltitudeEstimation#10]
A possible approach:
Start by simply substituting the rangefinder for the baro, then see whether all three (rangefinder, baro, accel) could be incorporated. One thing worth looking into is the AGL (Above Ground Level) versus ASL (Above Sea Level) issue. An optimal solution would probably compute ASL, and would have some conditional like "If rangefinder reading changes suddenly (faster than some threshold) while baro remains constant (or gradual), vehicle is above a ground obstacle, and ASL is unchanged"

**Comment by juangallostra** [comment]
A possible approach would be to place the rangefinder looking upwards. This way obstacles do not affect the measurements. Think about it.

**Comment by simondlevy** [comment]
Clever idea -- but how about going through doorways? ;^)

**Comment by juangallostra** [comment]
I am switching to another approach in order to perform altitude estimation. So far it looks more promising: https://github.com/juangallostra/Range-Baro-AltitudeEstimation.

Closing the issue since I don't think I will work anymore on this.
