### ISSUE TITLE
cmath.h ?

### ISSUE THREAD

**Issue by Pascal66** [juangallostra/AltitudeEstimation#12]
Seems (for me) that i cant find the cmath library needed by filter.h

**Comment by juangallostra** [comment]
Hi @Pascal66 , how are you trying to compile the library? Via the Arduino IDE?

**Comment by Pascal66** [comment]
Yes sorry Arduino IDE1.8.8

**Comment by Pascal66** [comment]
Made a little modification : PR #13

**Comment by juangallostra** [comment]
Closed as per PR #13
