### ISSUE TITLE
Updated tags in order to reflect latest changes in PlatformIO

### ISSUE THREAD

**Issue by romatou18** [juangallostra/AltitudeEstimation#15]
Hi @juangallostra ,

Thanks a lot for your great work, thanks @simondlevy  I also read your absolutely incredible tutorial on Kalman and complementary filters. Just so much better than any white paper or tutorial I could find anywhere else. The Matlab guys have good videos but still lose people in maths, because they love it, but for an average developer understanding the concepts and having the jigsaw together, before looking into deconstructing it piece by piece is just what matters, the rest usually follows using libs and detailed tutorials.

Anyhow, PlatformIO is a great tool to expose your work and i got to know about it thanks to this great platform. However it does not seem to download the latest version of your Altitude estimator since the last tag v0.2 is 14 commits behind the master head and it does not seem to pull the master head by default but the latest tag.

Because of this the old version using i.e. the #include <cmath> is still the default, the examples are also behind.

I thought I'd let you know as i got caught, but being familiar with git this was not an issue finding out, but many IOT hobbyist will bump into it.

Regards
Romain developer at Flightcell International (Rescue, police, firefighter helicopters and fixed wing flight tracking solutions)

![image](https://user-images.githubusercontent.com/60049000/80042428-0cb21a80-8553-11ea-85ab-360ec7581852.png)

**Comment by juangallostra** [comment]
@romatou18 thanks for pointing that out. 👍
